### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by fuelen** [elixir-cldr/cldr_calendars#9]
Elixir 1.13.1
```
==> ex_cldr_calendars
Compiling 24 files (.ex)

== Compilation error in file lib/cldr/calendar/calendars/iso_week.ex ==
** (MatchError) no match of right hand side value: #Cldr.LanguageTag<en-Latn-US [validated]>
    (ex_cldr 2.24.2) lib/cldr/locale.ex:1170: Cldr.Locale.first_match/3
    (ex_cldr 2.24.2) lib/cldr/locale.ex:1076: Cldr.Locale.gettext_locale_name/2
    (ex_cldr 2.24.2) lib/cldr/locale.ex:1047: Cldr.Locale.put_gettext_locale_name/2
    (ex_cldr 2.24.2) lib/cldr.ex:160: Cldr.get_locale/1
    lib/cldr/calendar/config.ex:102: Cldr.Calendar.Config.min_days_for_locale/2
    lib/cldr/calendar/config.ex:80: Cldr.Calendar.Config.extract_options/1
    expanding macro: Cldr.Calendar.Compiler.Week.__before_compile__/1
    lib/cldr/calendar/calendars/iso_week.ex:3: Cldr.Calendar.ISOWeek (module)
```

**Comment by kipcole9** [comment]
Thanks for the report. I'm not able to reproduce though - compiling on Elixir 1.13.1 is fine for me.  Would you mind sending the result of `mix hex.outdated` so I can see if there is a dependency version mismatch?

**Comment by fuelen** [comment]
I've removed `deps`, `_build` and now everything is ok.
Sorry for disturbing

**Comment by kipcole9** [comment]
Good to hear @fuelen, feel free to open issues any time, or post questions in the Elixir Forum.  Always glad to hear when someone is using `ex_cldr_calendars` since calendars are such an interesting topic to me - but not to many other people :-)  

I have a new library that implements lunisolar calendars like the Chinese, Japanese and Korean calendars coming out in the next couple of weeks as well.

**Comment by denispeplin** [comment]
For somebody who would stumble upon this issue: I had the same compilation error with VSCode and ElixirLS. Solved by upgrading VSCode that in turn upgraded ElixirLS.
After all upgrades, restart of VSCode is required.
